hosts: allhosts
tasks:
  - name: Build Docker Image
    command: 'docker build -t coredevops:latest .'
    
  - name: Deploy Container
    command: 'docker run -dit -p 5000:5000 coredevops:latest'
become: yes